name: jabba_index_generator_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.0-24.0.dev

dependencies:
  http: ^0.13.3
  pub_semver: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
