name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: dart-lang/setup-dart@7f54cd0cee53e120db0d1fce4196b7772ebd6f6e
        with:
          sdk: main
          flavor: raw

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run program
        run: dart run
      
      # - name: Deploy to Gist
      #   uses: exuanbo/actions-deploy-gist@v1
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     gist_id: f30f2c018335755f45bad1ad1a853899
      #     file_path: index.json
      
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/Baneeishaque/f30f2c018335755f45bad1ad1a853899
          github_file: index.json
